apiVersion: v1
kind: Service
metadata:
  name: php-website-service
spec:
  selector:
    app: php-website
  ports:
    - protocol: TCP
      port: 80        # Port inside the cluster that will be used to access the service
      targetPort: 81  # The port on the container that Apache listens on
  type: ClusterIP  # ClusterIP is the default and exposes the service only within the cluster
